---
apiVersion: v1
kind: Namespace
metadata:
  name: hyperservice
  labels:
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperservice-svc-{{serviceName}}-config
  namespace: "{{namespace}}"
data:
  SERVICE_NAME: "{{serviceName}}"
  HYPERSERVICE_WORKDIR_PATH: "{{workdir}}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperservice-pod-{{podName}}-config
  namespace: "{{namespace}}"
data:
  HYPERSERVICE_POD_NAME: "{{podName}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{podName}}"
  namespace: "{{namespace}}"
  labels:
    app: "{{podName}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{podName}}"
  template:
    metadata:
      labels:
        app: "{{podName}}"
    spec:
      containers:
        - name: "{{podName}}"
          image: "{{imageName}}:latest"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: hyperservice-svc-{{serviceName}}-env-var
          env:
            - name: KUMA_DPP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: hyperservice-svc-{{serviceName}}-config
                  key: SERVICE_NAME
            - name: HYPERSERVICE_WORKDIR_PATH
              valueFrom:
                configMapKeyRef:
                  name: hyperservice-svc-{{serviceName}}-config
                  key: HYPERSERVICE_WORKDIR_PATH
            - name: HYPERSERVICE_POD_NAME
              valueFrom:
                configMapKeyRef:
                  name: hyperservice-pod-{{podName}}-config
                  key: HYPERSERVICE_POD_NAME
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: hyperservice-workspace
              mountPath: "{{workdir}}"
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: hyperservice-workspace
          hostPath:
            path: "{{workdir}}"
            type: Directory
      nodeSelector:
        "kubernetes.io/hostname": "k3d-hyperservice-server-0"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{podName}}" # Nome dinâmico baseado na variáve}l
  namespace: "{{namespace}}"
  labels:
    app: "{{podName}}"
spec:
  selector:
    app: "{{podName}}"
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
