# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  include = [
    "cmd",
  ]
  exclude = [
    "tmp",
    "assets",
    "node_modules"
  ]

[log]
  time = true