apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-service-b-to-service-a
  namespace: hyperservice  # Ajuste conforme necessário
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: service-a_hyperservice_svc_3000  # Serviço de destino
  from:
    - targetRef:
        kind: MeshSubset
        tags:
          kuma.io/service: service-b_hyperservice_svc_3000  # Serviço que pode acessar
      default:
        action: Allow  # Permite o tráfego entre os serviços