apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-service-b-to-service-x
  namespace: hyperservice
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: service-x_hyperservice_svc_3000
  from:
    - targetRef:
        kind: MeshSubset
        tags:
          kuma.io/service: service-b_hyperservice_svc_3000
      default:
        action: Allow
