apiVersion: kuma.io/v1alpha1
kind: MeshPassthrough
metadata:
  name: passthrough-to-toolchains-sources
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshSubset
    proxyTypes:
      - Sidecar
    tags:
      k8s.kuma.io/namespace: hyperservice
  default:
    passthroughMode: Matched
    appendMatch:
      - type: Domain
        value: "github.com"
        protocol: tls
        port: 443
      - type: Domain
        value: "objects.githubusercontent.com"
        protocol: tls
        port: 443
      - type: Domain
        value: "registry.npmjs.org"
        protocol: tls
        port: 443
      - type: Domain
        value: "proxy.golang.org"
        protocol: tls
        port: 443
      - type: Domain
        value: "sum.golang.org"
        protocol: tls
        port: 443
        
