name: Build, Auto Versioning and Release Creation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: 'moonrepo/setup-toolchain@v0'
      - name: Clean up git lock file
        run: |
          rm -f .git/index.lock
      - name: Set Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      # Create bin directory before building
      - name: Build and version
        run: |
          moon ci :build 
          moon ci :version
      - name: Create Git Tag
        id: create_tag
        run: |
          VERSION="v$(date +%Y%m%d%H%M%S)"
          echo "Creating tag: $VERSION"
          git tag $VERSION
          git push origin $VERSION 
          echo "::set-output name=tag::$VERSION"
      - name: Generate GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            apps/hyperservice-device-app/bin/*
            apps/hyperservice-control-app/bin/*
            apps/hyperservice-cli/bin/*
          tag_name: ${{ steps.create_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 